version: "3"
services:
  app:
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - APP_NAME=api
      - APP_DATABASE_URL=mongodb://root:root@database:27017/
    depends_on:
      - database

  database:
    image: mongo:5
    restart: always
    expose:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
